apiVersion: v1
kind: ConfigMap
metadata:
  name: friends-config
  namespace: tds-group-3
data:
  PORT: "3000"
  DB_PORT: "5432"
  USERS_SERVICE_URL: "http://users:3000"
  NOTIFICATIONS_SERVICE_URL: "http://notifications:8080"
