apiVersion: v1
kind: Service
metadata:
  name: friends
  namespace: tds-group-3
  labels:
    app: friends
spec:
  type: ClusterIP
  selector:
    app: friends
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
